@baseUrl = http://localhost:8000/api
# Đổi token này thành token thật của bạn nếu đang dùng Auth
@token = 1|your_sanctum_token_here_xxxxxx

### 1. Lấy danh sách Mặc định (Trang 1, 10 dòng/trang, mới nhất lên đầu)
GET {{baseUrl}}/inventory-transactions
Accept: application/json
Authorization: Bearer {{token}}


### 2. Lọc theo Loại giao dịch (VD: Lấy toàn bộ lịch sử "Xuất kho")
GET {{baseUrl}}/inventory-transactions?type=OUT
Accept: application/json
Authorization: Bearer {{token}}


### 3. Lọc giao dịch của 1 Kho cụ thể từ đầu tháng đến nay
# Giả sử Kho Quận 1 có ID = 1
GET {{baseUrl}}/inventory-transactions?warehouse_id=1&from_date=2026-03-01
Accept: application/json
Authorization: Bearer {{token}}


### 4. Truy vết Lô hàng (Xem lô hàng ID=5 đã biến động ra sao)
GET {{baseUrl}}/inventory-transactions?product_batch_id=5
Accept: application/json
Authorization: Bearer {{token}}


### 5. Lọc kết hợp Sắp xếp và Phân trang tùy chỉnh (Dùng cho Data Table ở Frontend)
# Sắp xếp theo số lượng (quantity) tăng dần, lấy 5 dòng/trang
GET {{baseUrl}}/inventory-transactions?sort=quantity&order=asc&per_page=5
Accept: application/json
Authorization: Bearer {{token}}


### 6. Tìm theo người thao tác (Xem nhân viên ID=2 đã làm gì)
GET {{baseUrl}}/inventory-transactions?user_id=2
Accept: application/json
Authorization: Bearer {{token}}